### ISSUE TITLE
Package query segfault

### ISSUE THREAD

**Issue by qwazerty** [archlinuxfr/package-query#13]
Just notice a segfault when using with yaourt on the following args

```
$ yaourt python whatever
```

This command provoke the segfault
```
$ package-query -S -s -A python whatever
```

Seems to be reproducible on at least 2 installs.

Here is the backtrace in gdb
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7412c8e in __strcasestr_sse2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7412c8e in __strcasestr_sse2 () from /usr/lib/libc.so.6
#1  0x00000000004044ae in aur_request (targets=0x7fffffffe3f8, type=2) at aur.c:604
#2  0x000000000040487f in aur_search (targets=0x6119f0) at aur.c:692
#3  0x000000000040a73e in main (argc=6, argv=0x7fffffffe5e8) at package-query.c:543
```

**Comment by The-Compiler** [comment]
Also see https://github.com/archlinuxfr/yaourt/issues/133
